volumes:
  data:
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  backend:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
  front: 
    ports:
      - 3000:3000
    build:
      context: ./simple-store
      dockerfile: Dockerfile